#!/bin/bash

# Phase 2 (Week 2) Testing Script
# Camera & Media Capture Functionality

echo "================================"
echo "Phase 2 Testing: Camera & Media"
echo "================================"
echo ""
echo "Prerequisites:"
echo "- App running in Expo Go"
echo "- Camera and microphone permissions granted"
echo "- Logged in user"
echo ""
echo "Test Steps:"
echo ""
echo "CAMERA IMPLEMENTATION:"
echo "1. [ ] Camera opens when navigating to Camera tab"
echo "2. [ ] Tap capture button → Takes photo → Shows preview"
echo "3. [ ] Long press capture button → Records video (red indicator shows)"
echo "4. [ ] Release button or wait 10s → Video stops → Shows preview"
echo "5. [ ] Tap flash icon → Toggles between on/off"
echo "6. [ ] Tap flip icon → Switches between front/back camera"
echo ""
echo "MEDIA PREVIEW:"
echo "7. [ ] After capture → Preview shows fullscreen"
echo "8. [ ] Type in caption field → Text appears"
echo "9. [ ] Tap 'Retake' → Returns to camera"
echo "10. [ ] Tap 'Save to Gallery' → Media saves to device"
echo "11. [ ] Check device photos → Media appears in gallery"
echo ""
echo "EDGE CASES:"
echo "12. [ ] Take photo with flash on → Flash fires"
echo "13. [ ] Record video with front camera → Works correctly"
echo "14. [ ] Try to record while already recording → Ignored"
echo "15. [ ] Navigate away during recording → Recording stops"
echo ""
echo "VERIFICATION:"
echo "✓ All camera controls functional"
echo "✓ Photo capture works reliably"
echo "✓ Video recording completes (no hanging)"
echo "✓ 10-second limit enforced"
echo "✓ Media preview displays correctly"
echo "✓ Caption, retake, save all work"
echo ""
echo "Known Issues Fixed:"
echo "- Video recording hang resolved (newArchEnabled:false + mode='video')"
echo "- See POT-16 for details"
echo ""
echo "Exit Criteria Met:"
echo "- [ ] Camera opens when app launches (via tab navigation)"
echo "- [ ] Can capture photos"
echo "- [ ] Can record videos up to 10 seconds"
echo "- [ ] Camera controls work"
echo "- [ ] Preview shows after capture"
echo "- [ ] Can add caption text"
echo "- [ ] Can save to device gallery"
echo "- [ ] Can retake photo/video"